### ISSUE TITLE
Plugin.BLE

### ISSUE THREAD

**Issue by jenscski** [cslrfid/CS108-Mobile-CSharp-DotNetStd-App-v4#12]
Hello, 

Is there a reason you have your own version of the Plugin.BLE library?
And not using the original library as NuGet?

https://github.com/xabre/xamarin-bluetooth-le
https://www.nuget.org/packages/Plugin.BLE

**Comment by jenscski** [comment]
@ksclam

**Comment by ksclam** [comment]
It is a direct pull from the original Plugin.BLE on GitHub so if you are not using Mvvmcross, you can remove the local project dependences (Plugin.BLE.Abstractions) on the library CSLibrary-NETStandard and then add the Nuget package Plugin.BLE back to the project.  Then, develop the app without the Mvvmcross wrapper.

Your application will need to make connection to the reader through the BLE plugin same way as on the demo app.  Then, making calls to the CSLibrary for data access.

This allows you to develop with native Xamarin or Xamarin.Forms

Thanks.
